# Generated by Django 3.2.4 on 2021-06-26 18:28

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(choices=[('Employer', 'Employer'), ('Employee', 'Employee')], max_length=20)),
                ('userImage', models.ImageField(default='media/default/job-offer-on-orange-note-260nw-752376046.jpg', upload_to=accounts.models.image_upload)),
                ('verfication', models.BinaryField(default=False)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
