# Generated by Django 3.2.4 on 2021-06-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertips',
            name='verfication',
            field=models.BooleanField(default=False),
        ),
    ]
