# Generated by Django 3.2.4 on 2021-06-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usertips_verfication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertips',
            name='userType',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Employer', 'Employer')], max_length=20),
        ),
    ]
