# Generated by Django 3.2.4 on 2021-06-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_job_type'),
        ('accounts', '0002_alter_usertips_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertips',
            name='job_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertips',
            name='userType',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Employer', 'Employer')], max_length=20),
        ),
    ]
