# Generated by Django 3.1.2 on 2020-10-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201030_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('employeer', 'you want to hire'), ('employee', 'you want a job')], max_length=50),
        ),
    ]
