# Generated by Django 3.2.4 on 2021-06-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210624_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertips',
            name='userType',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Employee', 'Employee')], max_length=20),
        ),
    ]
