# Generated by Django 3.1.2 on 2020-10-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201030_1643'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='Phone'),
        ),
    ]
