# Generated by Django 4.1.1 on 2022-09-26 15:37

from django.db import migrations, models
import home.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=home.models.file_upload)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
