# Generated by Django 3.1.2 on 2020-11-01 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import job.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'you shoould enter valid name'}, max_length=30)),
                ('job_type', models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], error_messages={'required': "Can't be Null"}, max_length=20)),
                ('description', models.TextField(error_messages={'required': 'enter valid message to get people like job require'}, max_length=1000)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('salary', models.IntegerField(error_messages={'required': 'required salary'})),
                ('vacancy', models.IntegerField(default=1)),
                ('image', models.ImageField(default='jobs/defaults/B612_20201021_094946_455.jpg', upload_to=job.models.image_upload)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(error_messages={'required': 'you should add categry'}, on_delete=django.db.models.deletion.CASCADE, to='job.category')),
                ('owner', models.ForeignKey(error_messages={'required': 'you should login first'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'Enter a Valid name'}, max_length=40)),
                ('email', models.EmailField(error_messages={'required': 'Enter a Valid Email'}, max_length=254, unique=True)),
                ('website', models.URLField(error_messages={'required': 'Enter a Valid website'})),
                ('cv', models.FileField(error_messages={'required': 'upload your cv'}, upload_to='jobs/cvs/')),
                ('cover', models.TextField(error_messages={'required': 'enter message to get hired'}, max_length=500)),
                ('app_date', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='job.job')),
            ],
        ),
    ]
