# Generated by Django 3.2.4 on 2021-06-15 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.category', verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Part Time', 'Part Time'), ('Remotly', 'Remotly'), ('Full Time', 'Full Time')], max_length=50),
        ),
    ]
