# Generated by Django 3.1.2 on 2020-10-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='jobs/B612_20201021_094946_455.jpg', upload_to='jobs/'),
        ),
    ]
