# Generated by Django 3.1.2 on 2020-10-24 07:21

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default='jobs/defaults/B612_20201021_094946_455.jpg', upload_to=job.models.image_upload),
        ),
    ]
