# Generated by Django 3.2.4 on 2021-06-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210615_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='jobs/default/job-offer-on-orange-note-260nw-752376046.jpg', upload_to='jobs/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Remotly', 'Remotly'), ('Internship', 'Internship')], max_length=50),
        ),
    ]
