# Generated by Django 3.2.4 on 2021-06-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210616_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default='media/jobs/default/job-offer-on-orange-note-260nw-752376046.jpg', upload_to='media/jobs/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Internship', 'Internship'), ('Remotly', 'Remotly'), ('Part Time', 'Part Time')], max_length=50),
        ),
    ]
