# Generated by Django 3.2.4 on 2021-06-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210616_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default='media/default/job-offer-on-orange-note-260nw-752376046.jpg', upload_to='media/jobs/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Remotly', 'Remotly'), ('Internship', 'Internship'), ('Part Time', 'Part Time'), ('Full Time', 'Full Time')], max_length=50),
        ),
    ]
