# Generated by Django 3.2.4 on 2021-06-16 02:41

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20210616_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default='media/default/job-offer-on-orange-note-260nw-752376046.jpg', upload_to=job.models.image_upload),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Remotly', 'Remotly'), ('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Internship', 'Internship')], max_length=50),
        ),
    ]
