# Generated by Django 3.1.2 on 2020-10-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='app_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
