# Generated by Django 3.2.4 on 2021-06-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20210618_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jobId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.job', verbose_name='Job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Remotly', 'Remotly'), ('Internship', 'Internship')], max_length=50),
        ),
    ]
